{% set version = "6.5.1" %}

package:
  name: jupyter_console
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-{{ version }}.tar.gz
  sha256: 6b91b7b6e8a715053b536db209a2f4b02429d7b28db27373a56a26b0bebd620b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-console = jupyter_console.app:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyter_client >=7.0.0
    - ipython
    - ipykernel
    - prompt_toolkit >=2.0.0,<3.1.0,!=3.0.0,!=3.0.1
    - pygments

test:
  commands:
    - jupyter-console -h
  imports:
    - jupyter_console

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter terminal console

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - blink1073
    - Carreau
    - davidbrochart
