{% set version = "5.1.0" %}

package:
  name: jupyter_console
  version: {{ version }}

source:
  fn: jupyter_console-{{ version }}.tar.gz
  url: https://github.com/jupyter/jupyter_console/archive/{{ version }}.tar.gz
  sha256: bee20976846123eda49ca880a84e567edd184c28a0ddcbbc0d990d2d8822e8e1

build:
  number: 0
  script: python -m pip install --no-deps .
  entry_points:
    - jupyter-console = jupyter_console.app:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - jupyter_client
    - ipython
    - ipykernel
    - prompt_toolkit
    - pygments
    - pexpect  # [not win]

test:
  commands:
    - jupyter-console -h
  imports:
    - jupyter_console

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  summary: Jupyter terminal console

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
