{% set version = "6.4.1" %}

package:
  name: jupyter_console
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-{{ version }}.tar.gz
  sha256: e098ff6338b7dacc91e9a2361e966d2f0b7c897aa4be074f05798d2dc6c19fc2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-console = jupyter_console.app:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jupyter_client <7.0.0
    - ipython
    - ipykernel
    - prompt_toolkit >=2.0.0,<3.1.0,!=3.0.0,!=3.0.1
    - pygments

test:
  commands:
    - jupyter-console -h
  imports:
    - jupyter_console

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter terminal console

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - blink1073
    - Carreau
    - davidbrochart
