{% set version = "6.6.0" %}

package:
  name: jupyter_console
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-{{ version }}.tar.gz
  sha256: 0ce8b5596df6b2453d56d1127aaa3e7b0e3c8fb73d48dcc77162753019b78215

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-console = jupyter_console.app:main

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.5
  run:
    - python >=3.7
    - jupyter_client >=7.0.0
    - ipython
    - ipykernel >=6.14
    - jupyter_core >=4.12,!=5.0.*
    - prompt_toolkit >=3.0.30
    - pyzmq >=17
    - traitlets >=5.4
    - pygments

test:
  commands:
    - jupyter-console -h
  imports:
    - jupyter_console

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter terminal console

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
    - blink1073
    - Carreau
    - davidbrochart
